#!/bin/sh
## cgr.sh for wow in /home/benoit.pingris/bin
## 
## Made by benoit pingris
## Login   <benoit.pingris@epitech.net>
## 
## Started on  Fri Jun 16 20:32:33 2017 benoit pingris
## Last update Fri Jun 16 20:51:14 2017 benoit pingris
##

repo_name=$1

##Catch the working direcory name
dir_name=`basename $(pwd)`

if [ "$repo_name" = "" ]; then
    echo "Reposotory to be created on Github (hit enter to use '$dir_name')?"
    read repo_name
fi


##If the user press enter, take the working directory as name
if [ "$repo_name" = "" ]; then
    repo_name=$dir_name
fi

##Take the username of the github account
username=`git config github.user`
if [ "$username" = "" ]; then
    echo "Could not find username, run 'git config --global github.user <username>'"
    invalid_credentials=1
fi


##Take the password of the github account
token=`git config github.token`
if [ "$token" = "" ]; then
    echo "Could not find token, run 'git config --global github.token <token>'"
    invalid_credentials=1
fi

##If logins are bad, exit the script
if [ "$invalid_credentials" == "1" ]; then
    exit 1
fi

##Creating the repository using the API
echo -n "Creating Github repository '$repo_name' ..."
curl -u "$username:$token" https://api.github.com/user/repos -d '{"name":"'$repo_name'"}' > /dev/null 2>&1
echo " done."

##Basic initialisation of the reposiry 
echo -n "Pushing local code to remote ..."
git init
git add --all
git commit -m "First commit !"
git remote add origin git@github.com:$username/$repo_name.git > /dev/null 2>&1
git push -u origin master
echo "All files have been pushed !"
